[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true}
validator= { workspace = true}